// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBljlczUe6bwcDgU36oyzK0YFAjZQlrK2s',
    appId: '1:272845289191:web:2273b06620210758535442',
    messagingSenderId: '272845289191',
    projectId: 'fir-seguro-app',
    authDomain: 'fir-seguro-app.firebaseapp.com',
    storageBucket: 'fir-seguro-app.firebasestorage.app',
    measurementId: 'G-CZJ26X7ZW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvr0NUU4CXUIsJu0GoYW0qKncy5LBVSw',
    appId: '1:272845289191:android:81d867aaacfc0146535442',
    messagingSenderId: '272845289191',
    projectId: 'fir-seguro-app',
    storageBucket: 'fir-seguro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGbq8WDyAtz9NP5FTijlUDdT5EHo_7DSI',
    appId: '1:272845289191:ios:baa627c2b2634590535442',
    messagingSenderId: '272845289191',
    projectId: 'fir-seguro-app',
    storageBucket: 'fir-seguro-app.firebasestorage.app',
    iosBundleId: 'com.example.demoSeguroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGbq8WDyAtz9NP5FTijlUDdT5EHo_7DSI',
    appId: '1:272845289191:ios:baa627c2b2634590535442',
    messagingSenderId: '272845289191',
    projectId: 'fir-seguro-app',
    storageBucket: 'fir-seguro-app.firebasestorage.app',
    iosBundleId: 'com.example.demoSeguroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBljlczUe6bwcDgU36oyzK0YFAjZQlrK2s',
    appId: '1:272845289191:web:ff9956e0ed568b25535442',
    messagingSenderId: '272845289191',
    projectId: 'fir-seguro-app',
    authDomain: 'fir-seguro-app.firebaseapp.com',
    storageBucket: 'fir-seguro-app.firebasestorage.app',
    measurementId: 'G-R23LQ1DDWX',
  );

}