name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    # Esta condição impede que PRs de forks externos tentem rodar (segurança)
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PASSO NOVO: Instala o Java (Recomendado para setup do ambiente)
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # PASSO NOVO: Instala o Flutter na máquina do GitHub
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # PASSO NOVO: Baixa as dependências
      - run: flutter pub get

      # PASSO NOVO: Compila o projeto Web antes de enviar
      - run: flutter build web --release

      # Deploy: Envia para um canal de PREVIEW (link temporário)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_SEGURO_APP }}
          projectId: fir-seguro-app
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks